#!/usr/bin/env bash
# build.sh -- regenerate brain/index.md (catalog).
#
# Sections: categorized files | per-entity pages | sources.
# Idempotent. Skips silently if no brain dir.

set -u

BRAIN_DIR="${BRAIN_DIR:-$HOME/brain}"
NANOBRAIN_DIR="${NANOBRAIN_DIR:-$HOME/Documents/nanobrain-v2}"

if [ ! -d "$BRAIN_DIR/brain" ]; then
  echo "[brain-index] no brain dir: $BRAIN_DIR/brain" >&2
  exit 0
fi

INDEX="$BRAIN_DIR/brain/index.md"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

TS=$(date '+%Y-%m-%d %H:%M')

# Hardcoded one-liner summaries for category files.
summary_for() {
  case "$1" in
    self.md)         echo "Identity, voice, principles" ;;
    goals.md)        echo "Goals, priorities, tradeoff filters" ;;
    decisions.md)    echo "Material decisions with rationale" ;;
    learnings.md)    echo "Non-obvious insights" ;;
    projects.md)     echo "Active projects (index)" ;;
    people.md)       echo "Contacts (index)" ;;
    interactions.md) echo "Append-only interaction log" ;;
    *)               echo "" ;;
  esac
}

# Count `^### ` entries in a file. grep -c returns N on stdout and exit 1 if
# zero matches, which combined with "|| echo 0" double-printed. Suppress the
# exit code by always exiting 0 from the helper.
count_entries() {
  if [ -f "$1" ]; then
    n=$(grep -c '^### ' "$1" 2>/dev/null || true)
    [ -n "$n" ] && echo "$n" || echo 0
  else
    echo 0
  fi
}

# Last-touched: prefer git log; fall back to file mtime; else "-".
last_touched() {
  local f="$1"
  if [ -d "$BRAIN_DIR/.git" ]; then
    local d
    d=$(cd "$BRAIN_DIR" && git log -1 --format=%cs -- "${f#$BRAIN_DIR/}" 2>/dev/null || true)
    if [ -n "$d" ]; then
      printf '%s' "$d"
      return
    fi
  fi
  if [ -f "$f" ]; then
    if date -r "$f" '+%Y-%m-%d' 2>/dev/null; then return; fi
    date -u -r "$(stat -f %m "$f" 2>/dev/null || stat -c %Y "$f" 2>/dev/null)" '+%Y-%m-%d' 2>/dev/null || echo "-"
    return
  fi
  echo "-"
}

# First non-empty line after a `# Title` heading (skipping blanks).
first_summary_line() {
  local f="$1"
  awk '
    /^# / && !seen { seen = 1; next }
    seen && NF > 0 { print; exit }
  ' "$f" 2>/dev/null
}

slugify_filename() {
  basename "$1" .md
}

{
  printf '# Index\n\n'
  printf '_Auto-generated by /brain-index. Last updated: %s._\n\n' "$TS"

  # Section 1: categorized files.
  printf '## Categorized files\n\n'
  printf '| File | Entries | Last touched | Summary |\n'
  printf '|---|---|---|---|\n'
  for f in self.md goals.md decisions.md learnings.md projects.md people.md interactions.md; do
    fp="$BRAIN_DIR/brain/$f"
    n=$(count_entries "$fp")
    lt=$(last_touched "$fp")
    sm=$(summary_for "$f")
    if [ -f "$fp" ]; then
      printf '| [%s](%s) | %s | %s | %s |\n' "$f" "$f" "$n" "$lt" "$sm"
    fi
  done
  printf '\n'

  # Section 2: per-entity pages.
  has_people=0
  has_projects=0
  [ -d "$BRAIN_DIR/brain/people" ] && ls "$BRAIN_DIR/brain/people"/*.md >/dev/null 2>&1 && has_people=1
  [ -d "$BRAIN_DIR/brain/projects" ] && ls "$BRAIN_DIR/brain/projects"/*.md >/dev/null 2>&1 && has_projects=1

  if [ "$has_people" -eq 1 ] || [ "$has_projects" -eq 1 ]; then
    printf '## Per-entity pages\n\n'

    if [ "$has_people" -eq 1 ]; then
      printf '### People\n'
      for p in "$BRAIN_DIR"/brain/people/*.md; do
        [ -f "$p" ] || continue
        slug=$(slugify_filename "$p")
        sm=$(first_summary_line "$p")
        if [ -n "$sm" ]; then
          printf -- '- [%s.md](people/%s.md) -- %s\n' "$slug" "$slug" "$sm"
        else
          printf -- '- [%s.md](people/%s.md)\n' "$slug" "$slug"
        fi
      done
      printf '\n'
    fi

    if [ "$has_projects" -eq 1 ]; then
      printf '### Projects\n'
      for p in "$BRAIN_DIR"/brain/projects/*.md; do
        [ -f "$p" ] || continue
        slug=$(slugify_filename "$p")
        sm=$(first_summary_line "$p")
        if [ -n "$sm" ]; then
          printf -- '- [%s.md](projects/%s.md) -- %s\n' "$slug" "$slug" "$sm"
        else
          printf -- '- [%s.md](projects/%s.md)\n' "$slug" "$slug"
        fi
      done
      printf '\n'
    fi
  fi

  # Section 3: sources.
  if [ -d "$BRAIN_DIR/data" ]; then
    has_sources=0
    for d in "$BRAIN_DIR"/data/*/; do
      [ -f "${d}INBOX.md" ] && has_sources=1 && break
    done

    if [ "$has_sources" -eq 1 ]; then
      printf '## Sources\n\n'
      printf '| Source | INBOX entries | Last ingest |\n'
      printf '|---|---|---|\n'
      for d in "$BRAIN_DIR"/data/*/; do
        inbox="${d}INBOX.md"
        [ -f "$inbox" ] || continue
        src=$(basename "$d")
        case "$src" in _*) continue ;; esac
        n=$(count_entries "$inbox")
        lt=$(last_touched "$inbox")
        printf '| %s | %s | %s |\n' "$src" "$n" "$lt"
      done
      printf '\n'
    fi
  fi
} > "$TMP"

mv "$TMP" "$INDEX"
trap - EXIT

echo "[brain-index] regenerated: $INDEX"

LOG_SH="$NANOBRAIN_DIR/code/skills/brain-log/log.sh"
if [ -x "$LOG_SH" ]; then
  BRAIN_DIR="$BRAIN_DIR" bash "$LOG_SH" index "rebuilt brain/index.md" || true
fi
